# Trigger workflow after AWS Account ID fix
name: Build and Push to ECR

on:
  push:
    branches:
      - main   # run workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Step 3: Login to AWS ECR
      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region eu-west-2 \
          | docker login --username AWS --password-stdin \
            430006376054.dkr.ecr.eu-west-2.amazonaws.com

      # Step 4: Build and push Docker image
      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_REPO_NAME=fastapi-app
          IMAGE_TAG=latest
          ACCOUNT_ID=430006376054

          # Build Docker image
          docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

          # Tag image for ECR
          docker tag $IMAGE_REPO_NAME:$IMAGE_TAG \
            $ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

          # Push to ECR
          docker push $ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
